Repository avaframe/AvaFrame, pull requests merged in 2020-10, with the labels that each got.

#130 fixAB
  avaframe/in2Trans/geoTrans.py
Labels: bug

#139 updating dfa docs
  docs/_static/css/custom.css
  docs/appendixCom1DFA.rst
  docs/conf.py
  docs/moduleCom1DFA.rst
Labels: documentation

#150 read local generalcfg.ini
  avaframe/in3Utils/cfgUtils.py
Labels: enhancement

#163 link to documentation to the com1DFA_Exe repository
  docs/moduleCom1DFA.rst
Labels: documentation

#170 Add all standard tests to pytest
  avaframe/tests/test_com1DFA.py
  benchmarks/simParameters.py
Labels: enhancement
