Repository avaframe/AvaFrame, pull requests merged in 2020-12, with the labels that each got.

#237 Update docs
  docs/develop.rst
Labels: documentation

#247 Remove defaultCellSize setting; fixes #207
  avaframe/com1DFA/CreateProject.cint
  avaframe/com1DFA/com1DFA.py
Labels: bug

#250 Correct info on release areas
  avaframe/log2Report/generateReport.py
  benchmarks/simParameters.py
Labels: bug

#251 Add release notes for v0.2
  docs/releaseNotes.rst
Labels: documentation

#256 Add option to enter Start:End:Steps for arrays in INI files
  avaframe/com1DFA/com1DFA.py
  avaframe/com1DFA/com1DFACfg.ini
  avaframe/runVariationsTests.py
  benchmarks/avaAlr/avaAlr_com1DFACfg.ini
  benchmarks/avaBowl/avaBowl_com1DFACfg.ini
  benchmarks/avaFlatPlane/avaFlatPlaneVarPar_com1DFACfg.ini
  benchmarks/avaFlatPlane/avaFlatPlane_com1DFACfg.ini
  benchmarks/avaHelix/avaHelix_com1DFACfg.ini
  benchmarks/avaHelixChannel/avaHelixChannelVarPar_com1DFACfg.ini
  benchmarks/avaHelixChannel/avaHelixChannel_com1DFACfg.ini
  benchmarks/avaHit/avaHit_com1DFACfg.ini
  benchmarks/avaHockey/avaHockeyVarPar_com1DFACfg.ini
  benchmarks/avaHockey/avaHockey_com1DFACfg.ini
  benchmarks/avaHockeySmoothSmall/avaHockeySmoothSmall_com1DFACfg.ini
  benchmarks/avaInclinedPlane/avaInclinedPlane_com1DFACfg.ini
  benchmarks/avaKot/avaKot_com1DFACfg.ini
  benchmarks/avaMal/avaMal_com1DFACfg.ini
  benchmarks/avaWog/avaWog_com1DFACfg.ini
  benchmarks/simParametersVar.py
Labels: enhancement
