Repository avaframe/AvaFrame, pull requests merged in 2021-09, with the labels that each got.

#535 Update plot tests
  avaframe/tests/test_plotUtils.py
Labels: testing

#536 fix error in explicit friction force and add pytests for cython
  avaframe/com1DFA/DFAfunctionsCython.pyx
  avaframe/tests/test_DFAfunctionsCython.py
Labels: bug, testing

#540 Add note about meshCellSize and mPPDIR
  docs/com1DFAAlgorithm.rst
Labels: documentation

#552 fix testFP
  avaframe/ana1Tests/FPtest.py
  avaframe/out1Peak/outPlotAllPeak.py
Labels: bug
