Repository avaframe/AvaFrame, pull requests merged in 2021-04, with the labels that each got.

#392 solve issue if diff is zero for diff plot
  avaframe/out3Plot/outQuickPlot.py
Labels: enhancement

#413 Add new topography 3D plotting style
  avaframe/out3Plot/outTopo.py
  avaframe/runPlotTopo.py
Labels: enhancement

#414 make buffer constrained plot function available
  avaframe/out1Peak/outPlotAllPeak.py
  avaframe/out3Plot/plotUtils.py
Labels: enhancement

#417 make remesh work with noData
  avaframe/in3Utils/geoTrans.py
Labels: bug, com1DFAdev

#428 Update com1DFA docu
  docs/moduleCom1DFA.rst
Labels: documentation
