Repository avaframe/AvaFrame, pull requests merged in 2022-11, with the labels that each got.

#777 add filtering for greater or smaller than
  avaframe/in3Utils/cfgHandling.py
  avaframe/in3Utils/fileHandlerUtils.py
  avaframe/tests/test_cfgHandling.py
  avaframe/tests/test_fileHandlerUtils.py
Labels: enhancement

#778 add contour plot to aimec
  avaframe/ana3AIMEC/aimecTools.py
  avaframe/ana3AIMEC/ana3AIMEC.py
  avaframe/ana4Stats/probAna.py
  avaframe/out3Plot/outAIMEC.py
  avaframe/out3Plot/outQuickPlot.py
  avaframe/out3Plot/plotUtils.py
  avaframe/out3Plot/statsPlots.py
  avaframe/runScripts/runProbAnaCom1DFA.py
  avaframe/tests/test_ana3AIMEC.py
Labels: enhancement

#785 add ref sim to contour plot
  avaframe/ana3AIMEC/aimecTools.py
  avaframe/out3Plot/outAIMEC.py
  avaframe/runScripts/runAna3AIMEC.py
  avaframe/tests/test_aimecTools.py
  avaframe/tests/test_ana3AIMEC.py
Labels: enhancement, featureRequest

#786 Fix approach velocity for rangeTimeDiagram; Issue #782
  avaframe/ana5Utils/distanceTimeAnalysis.py
  avaframe/runScripts/runRangeTimeDiagram.py
  avaframe/tests/test_distanceTimeAnalysis.py
Labels: bug

#783 Update com1DFA dam documentation
  docs/com1DFAAlgorithm.rst
  docs/damToolCom1DFA.rst
  docs/index.rst
  docs/moduleCom1DFA.rst
  docs/theoryCom1DFA.rst
Labels: documentation
