Repository avaframe/AvaFrame, pull requests merged in 2022-01, with the labels that each got.

#632 remove default type from prob Run add passing cfgFileMod option
  avaframe/ana4Stats/probAna.py
  avaframe/ana4Stats/probAnaCfg.ini
  avaframe/runScripts/runProbAnaCom1DFA.py
Labels: enhancement

#636 update thickness settings docu
  docs/moduleCom1DFA.rst
Labels: documentation

#643 update runScripts
  avaframe/data/avaDamBreak/Inputs/damBreak_com1DFACfg.ini
  avaframe/runScripts/runExportToCsv.py
  avaframe/runScripts/runProbAna.py
  avaframe/runScripts/runStatsExample.py
Labels: bug

#644 udpate comparison script
  avaframe/runScripts/runCompareCom1DFAvsCom1DFAOrig.py
Labels: bug

#648 add entres type and particles to list
  avaframe/com1DFA/com1DFA.py
  avaframe/in1Data/getInput.py
Labels: bug

#652 add runScripts to generate comparison reports
  avaframe/runScripts/runCompareCom1DFAvsCom1DFAOrigEnt.py
  avaframe/runScripts/runCompareCom1DFAvsCom1DFAOrigNull.py
  avaframe/runScripts/runCompareCom1DFAvsCom1DFAOrigRes.py
Labels: enhancement

#655 add aimec stats writing for report
  avaframe/ana3AIMEC/ana3AIMEC.py
Labels: enhancement
