Repository avaframe/AvaFrame, pull requests merged in 2022-09, with the labels that each got.

#765 adjust remeshDEM
  avaframe/in3Utils/geoTrans.py
  benchmarks/avaBowlNullTest/avaBowlNullTest_desDict.json
  benchmarks/avaBowlNullTest/avaBowl_com1DFACfg.ini
Labels: bug

#766 Update installation instructions; fixes #764
  docs/operational.rst
  docs/operationalGerman.rst
Labels: documentation

#755 Animate tt
  avaframe/ana5Utils/distanceTimeAnalysis.py
  avaframe/ana5Utils/distanceTimeAnalysisCfg.ini
  avaframe/com1DFA/com1DFA.py
  avaframe/out3Plot/outDistanceTimeAnalysis.py
  avaframe/out3Plot/plotUtils.py
  avaframe/runScripts/runRangeTimeDiagram.py
  avaframe/runScripts/runThalwegTimeDiagram.py
  avaframe/tests/test_distanceTimeAnalysis.py
  avaframe/tests/test_fileHandlerUtils.py
  avaframe/tests/test_outDistanceTimeAnalysis.py
  avaframe/tests/test_plotUtils.py
Labels: enhancement

#769 fix for missing contour label in legend; fixes #768
  avaframe/out3Plot/statsPlots.py
Labels: bug

#767 creating more stats plots
  avaframe/out3Plot/outAIMEC.py
  avaframe/out3Plot/statsPlots.py
  avaframe/runScripts/runStatsPlots.py
Labels: enhancement

#770 update figure title for probmap
  avaframe/out3Plot/statsPlots.py
Labels: enhancement
