Repository avaframe/AvaFrame, pull requests merged in 2023-09, with the labels that each got.

#898 Fix ranges plot
  avaframe/out3Plot/outParticlesAnalysis.py
Labels: bug

#902 Change separator and float format in relStats csv [com1]
  avaframe/in1Data/getInput.py
Labels: enhancement

#903 Add pdf output to readthedocs
  .readthedocs.yml
Labels: documentation

#905 allow to pass dem [ana3]
  avaframe/ana3AIMEC/aimecTools.py
  avaframe/ana3AIMEC/ana3AIMEC.py
  avaframe/runScripts/runAna3AIMEC.py
Labels: enhancement

#916 fix bug in checking for matplotlibversion
  avaframe/out3Plot/plotUtils.py
Labels: bug

#911 changes topo gen to move topo in z direction [in3Utils]
  avaframe/in3Utils/generateTopo.py
  avaframe/in3Utils/generateTopoCfg.ini
Labels: enhancement

#912 Update py versions in GitHub workflows
  .github/workflows/releaseWithManylinux.yml
  .github/workflows/runTestSinglePython.yml
  avaframe/out3Plot/plotUtils.py
Labels: enhancement

#918 add ax object to aimec contour plot colorbar
  avaframe/out3Plot/outAIMEC.py
Labels: bug

#919 make name dependent on input in plot [out3Plot]
  avaframe/out3Plot/outAIMEC.py
Labels: bug
