Repository avaframe/AvaFrame, pull requests merged in 2023-01, with the labels that each got.

#801 fix unexpected keyword error
  avaframe/out3Plot/plotUtils.py
Labels: bug

#800 Add docu paragraph for wetSnow [com1DFA]
  docs/theoryCom1DFA.rst
Labels: documentation

#803 Fix saving plots and report generation [out3Plots][out1Peak]
  avaframe/avaframeCfg.ini
  avaframe/com1DFA/com1DFA.py
  avaframe/out1Peak/outPlotAllPeak.py
  avaframe/out3Plot/in1DataPlots.py
  avaframe/out3Plot/outQuickPlot.py
  avaframe/out3Plot/outTopo.py
  avaframe/out3Plot/statsPlots.py
  avaframe/tests/test_out1Peak.py
Labels: bug

#805 fix bug simName modelType, add sphKernelRadius setting option [com1DFA]
  avaframe/com1DFA/checkCfg.py
  avaframe/com1DFA/com1DFA.py
  avaframe/in3Utils/fileHandlerUtils.py
  avaframe/tests/test_com1DFA.py
  avaframe/tests/test_fileHandlerUtils.py
Labels: bug, enhancement

#811 Add com5GlideSnow documentation [com4GlideSnow]
  docs/index.rst
  docs/moduleCom1DFA.rst
  docs/moduleCom5GlideSnow.rst
Labels: documentation
