Repository avaframe/AvaFrame, pull requests merged in 2023-10, with the labels that each got.

#923 Adjust aimec min mean values with added zero mask [ana3]
  avaframe/ana3AIMEC/ana3AIMEC.py
  avaframe/ana3AIMEC/ana3AIMECCfg.ini
  avaframe/out3Plot/outAIMEC.py
  avaframe/tests/test_ana3AIMEC.py
Labels: enhancement

#924 Adjust float format of ReleaseStat to avoid Excel Problem
  avaframe/ana4Stats/probAna.py
  avaframe/com1DFA/com1DFATools.py
  avaframe/com1DFA/deriveParameterSet.py
  avaframe/in1Data/getInput.py
  avaframe/tests/test_getInput.py
  benchmarks/avaFlatPlaneNullTest/avaFlatPlane_AIMECCfg.ini
Labels: enhancement, featureRequest

#926 update run script tests
  avaframe/runStandardTestsCom1DFA.py
Labels: bug
