Repository avaframe/AvaFrame, pull requests merged in 2023-08, with the labels that each got.

#886 Prob plots [com1; out3; ana4]
  avaframe/ana4Stats/probAna.py
  avaframe/ana4Stats/probAnaCfg.ini
  avaframe/com1DFA/com1DFA.py
  avaframe/out3Plot/outAIMEC.py
  avaframe/out3Plot/outCom1DFA.py
  avaframe/out3Plot/outContours.py
  avaframe/out3Plot/outQuickPlot.py
  avaframe/out3Plot/plotUtils.py
  avaframe/out3Plot/statsPlots.py
  avaframe/runAna4ProbAna.py
  avaframe/runScripts/runProbAna.py
  avaframe/tests/data/testCom1DFA/probA_com1DFACfg.ini
  avaframe/tests/test_probAna.py
  benchmarks/avaHockeyChannelStatsTest/avaHockeyChannelProbAna_probAnaCfg.ini
Labels: enhancement

#892 add input read function [com1]
  avaframe/in1Data/getInput.py
Labels: enhancement

#895 add flag for label in contourplots [out3]
  avaframe/out3Plot/outQuickPlot.py
  avaframe/runAna4ProbAna.py
Labels: bug

#896 add optional input dir for aimec analysis
  avaframe/ana3AIMEC/aimecTools.py
  avaframe/ana3AIMEC/ana3AIMEC.py
  avaframe/ana3AIMEC/dfa2Aimec.py
  avaframe/com1DFA/com1DFACfg.ini
  avaframe/in1Data/getInput.py
  avaframe/out3Plot/outAIMEC.py
  avaframe/runScripts/runAna3AIMEC.py
  docs/moduleAna3AIMEC.rst
Labels: enhancement

#897 Fix docu
  avaframe/ana3AIMEC/aimecTools.py
  avaframe/in3Utils/getReleaseArea.py
  docs/theoryCom1DFA.rst
Labels: documentation

#900 Fix name problems in runStandardTests
  avaframe/in3Utils/fileHandlerUtils.py
  avaframe/runStandardTestsCom1DFA.py
Labels: bug
