Repository avaframe/AvaFrame, pull requests merged in 2023-11, with the labels that each got.

#942 add couomb min shear friction
  avaframe/com1DFA/DFAfunctionsCython.pyx
  avaframe/com1DFA/checkCfg.py
  avaframe/com1DFA/com1DFA.py
  avaframe/com1DFA/com1DFACfg.ini
Labels: enhancement

#940 Add L to simName for samosAT; fixes #930 [com1]
  avaframe/com1DFA/com1DFATools.py
  avaframe/in3Utils/fileHandlerUtils.py
  avaframe/tests/test_com1DFA.py
Labels: enhancement, featureRequest

#946 Set exists_ok on creation of dirs (for parallel computing) [in3]
  avaframe/in3Utils/fileHandlerUtils.py
Labels: bug
