Repository avaframe/AvaFrame, pull requests merged in 2023-03, with the labels that each got.

#826 Move check for default indicator [com1DFA]; fixes #825
  avaframe/com1DFA/com1DFA.py
Labels: bug

#827 add secrel info to report and write simisol error to csv
  avaframe/ana1Tests/simiSolTest.py
  avaframe/com1DFA/com1DFA.py
  avaframe/tests/test_com1DFA.py
Labels: enhancement

#831 Add missing elif in parallel imports [com1DFA]
  avaframe/com1DFA/com1DFA.py
Labels: bug

#830 Refactor glossary
  docs/glossary.rst
  docs/references_all.bib
Labels: documentation

#835 add remeshing result files for probMap [ana4Prop][out3plot]
  avaframe/ana4Stats/probAna.py
  avaframe/out3Plot/plotUtils.py
  avaframe/out3Plot/statsPlots.py
Labels: bug

#836 Make error on features outside DEM clearer [in2Trans]
  avaframe/in2Trans/shpConversion.py
  avaframe/tests/test_shpConversion.py
Labels: enhancement

#838 Add modelType to com5 cfg; remove kernel radius setting [com5]
  avaframe/com5GlideSnow/com5GlideSnowCfg.ini
Labels: enhancement

#839 add optional argument for general config
  avaframe/in3Utils/cfgUtils.py
  avaframe/in3Utils/logUtils.py
  avaframe/tests/data/local_testCfg.ini
  avaframe/tests/data/test2Cfg.ini
  avaframe/tests/test_cfgUtils.py
Labels: enhancement

#840 Fix boundary bug in plotUtils [ou3Plot]; add missing ini parameter [ana4]
  avaframe/ana4Stats/probAnaCfg.ini
  avaframe/out3Plot/plotUtils.py
Labels: bug
