Repository avaframe/AvaFrame, pull requests merged in 2023-06, with the labels that each got.

#861 Update probAna run script example
  avaframe/in1Data/getInput.py
  avaframe/out3Plot/statsPlots.py
  avaframe/runScripts/runProbAna.py
  avaframe/runScripts/runStatsExample.py
  benchmarks/avaHockeyChannelStatsTest/avaHockeyChannelProbAna_com1DFACfg.ini
  benchmarks/avaHockeyChannelStatsTest/avaHockeyChannelProbAna_probAnaCfg.ini
  docs/_static/avaHockeyChannel_probMap_lim1.0.png
  docs/moduleAna4Stats.rst
Labels: bug, documentation

#864 add RELTH to folderstruct [in3Utils]
  avaframe/in3Utils/initializeProject.py
Labels: enhancement

#865 Rename glidesnow to snowslide [com5]
  avaframe/com1DFA/DFAfunctionsCython.pyx
  avaframe/com1DFA/com1DFA.py
  avaframe/com1DFA/com1DFACfg.ini
  avaframe/com1DFA/particleTools.py
  avaframe/com5SnowSlide/__init__.py
  avaframe/com5SnowSlide/com5SnowSlide.py
  avaframe/com5SnowSlide/com5SnowSlideCfg.ini
  avaframe/out3Plot/outDebugPlots.py
  avaframe/runCom5SnowSlide.py
  avaframe/runScripts/runContourPlot.py
  avaframe/tests/test_DFAfunctionsCython.py
  avaframe/tests/test_snowSlide.py
  docs/com1DFAAlgorithm.rst
  docs/index.rst
  docs/moduleCom5SnowSlide.rst
Labels: enhancement

#867 Fix graphvix on rtd
  .readthedocs.yml
Labels: bug, documentation

#869 Prepare RelInfo for the connector [in1Data]
  avaframe/runAna4ProbAna.py
  avaframe/runIn1RelInfo.py
  avaframe/runScripts/runReleaseInfo.py
Labels: enhancement

#871 fix line in docu
  avaframe/out3Plot/outQuickPlot.py
  avaframe/tests/test_outQuickPlot.py
  docs/moduleOut3Plot.rst
Labels: bug, documentation, enhancement
