Repository avaframe/AvaFrame, pull requests merged in 2024-10, with the labels that each got.

#1031 Update Advanced Usage chapter in docs [doc]
  docs/advancedUsage.rst
  docs/configuration.rst
  docs/develop.rst
  docs/developinstall.rst
  docs/developinstallwin.rst
  docs/gettingstarted.rst
  docs/installation.rst
  docs/moduleCom1DFA.rst
Labels: documentation, enhancement

#1032 Add small indicator to com2AB outputs [com2]
  avaframe/out3Plot/outAB.py
  avaframe/runCom2AB.py
Labels: enhancement

#1033 Change default probAna range; fixes #967 [ana4]
  avaframe/ana4Stats/probAnaCfg.ini
Labels: enhancement, featureRequest

#1034 Change runout info altitude for friction adjustment (request by WLV) [doc]
  docs/theoryCom1DFA.rst
Labels: documentation, enhancement
