Repository avaframe/AvaFrame, pull requests merged in 2024-05, with the labels that each got.

#972 Modified documentation: resistance parameter [doc]
  docs/theoryCom1DFA.rst
Labels: documentation

#973 add option to write parameter variation config files through ana4Prob… [ana4]
  avaframe/ana4Stats/probAna.py
  avaframe/ana4Stats/probAnaCfg.ini
  avaframe/com4FlowPy/com4FlowPyCfg.ini
  avaframe/runScripts/runCreateProbCfgsFlowPy.py
Labels: enhancement

#977 Include py 3.12; add psutil requirement
  .github/workflows/releaseWithManylinux.yml
  setup.py
Labels: enhancement

#978 Remove python 3.7 from Windows and Mac os build
  .github/workflows/releaseWithManylinux.yml
  .github/workflows/runTestSinglePython.yml
Labels: enhancement

#979 Split release script in Macosx and windows matrix
  .github/workflows/releaseWithManylinux.yml
Labels: bug

#980 Adjust zenodo json, update release action
  .github/workflows/releaseWithManylinux.yml
  .zenodo.json
Labels: enhancement

#974 com4FlowPy bug-fixes/added functionality [com4]
  avaframe/com4FlowPy/com4FlowPy.py
  avaframe/com4FlowPy/com4FlowPyCfg.ini
  avaframe/com4FlowPy/flowClass.py
  avaframe/com4FlowPy/flowCore.py
  avaframe/com4FlowPy/rasterIo.py
  avaframe/com4FlowPy/readme.md
  avaframe/com4FlowPy/splitAndMerge.py
  avaframe/runCom4FlowPy.py
Labels: enhancement

#982 adjust extent of plots and add tests
  avaframe/ana4Stats/probAna.py
  avaframe/out1Peak/outPlotAllPeak.py
  avaframe/out3Plot/outCom1DFA.py
  avaframe/out3Plot/outDistanceTimeAnalysis.py
  avaframe/out3Plot/outParticlesAnalysis.py
  avaframe/out3Plot/outQuickPlot.py
  avaframe/out3Plot/plotUtils.py
  avaframe/out3Plot/statsPlots.py
  avaframe/tests/test_plotUtils.py
  docs/moduleOut3Plot.rst
Labels: bug

#976 functionality to create probMaps for peakfiles from different modules [ana4; out3]
  avaframe/ana4Stats/probAna.py
  avaframe/runAna4ProbAna.py
  avaframe/runProbAnalysisOnly.py
  avaframe/tests/test_probAna.py
  docs/moduleAna4Stats.rst
Labels: featureRequest
