Repository avaframe/AvaFrame, pull requests merged in 2024-06, with the labels that each got.

#988 Hotfix for installation problem (script install)
  docs/developinstall.rst
Labels: bug, documentation

#987 issue936 com4FlowPy documentation [doc]
  docs/_static/com4FlowPy/Flow-Py_chart.png
  docs/_static/com4FlowPy/Motivation_2d.png
  docs/_static/com4FlowPy/Neighbours.png
  docs/moduleCom4FlowPy.rst
  docs/references_all.bib
  docs/theoryCom4FlowPy.rst
Labels: documentation

#990 [com4FlowPy]: add travel length to output-files
  avaframe/com4FlowPy/com4FlowPy.py
  avaframe/com4FlowPy/flowCore.py
Labels: enhancement

#989 Immediate bugFixes to com4FlowPy and minor mode enhancement [com4]
  avaframe/com4FlowPy/com4FlowPy.py
  avaframe/com4FlowPy/com4FlowPyCfg.ini
  avaframe/com4FlowPy/flowClass.py
Labels: bug, enhancement
