Repository avaframe/AvaFrame, pull requests merged in 2024-07, with the labels that each got.

#996 [com4FlowPy] cell_counts BUG FIX and code simplification
  avaframe/com4FlowPy/flowCore.py
Labels: bug

#997 [com4FlowPy]: Add additional output: ForestInteraction Layer
  avaframe/com4FlowPy/com4FlowPy.py
  avaframe/com4FlowPy/com4FlowPyCfg.ini
  avaframe/com4FlowPy/flowClass.py
  avaframe/com4FlowPy/flowCore.py
  avaframe/com4FlowPy/splitAndMerge.py
  docs/moduleCom4FlowPy.rst
  docs/references_all.bib
Labels: enhancement

#999 add docu for aimec reference [ana3]
  avaframe/ana3AIMEC/aimecTools.py
  avaframe/ana3AIMEC/ana3AIMEC.py
  avaframe/out3Plot/outAIMEC.py
  avaframe/tests/test_aimecTools.py
  docs/_static/ana3AIMEC/avaAlr_referenceLineTransfo_refPoly.png
  docs/_static/ana3AIMEC/avaAlr_runoutLinesComparison_relAlr_50963401fb_D_M_null_dfa_poly.png
  docs/moduleAna3AIMEC.rst
Labels: documentation

#1008 change to array
  avaframe/in3Utils/geoTrans.py
Labels: enhancement
