Repository avaframe/AvaFrame, pull requests merged in 2025-03, with the labels that each got.

#1102 [ana3AIMEC]: correct comments
  avaframe/ana3AIMEC/ana3AIMECCfg.ini
Labels: enhancement

#1103 [in3] Problem with non-closed shape polygons
  avaframe/com1DFA/com1DFA.py
  avaframe/data/avaFlatPlane/Inputs/REL/release1FP.dbf
  avaframe/data/avaFlatPlane/Inputs/REL/release1FP.shp
  avaframe/data/avaFlatPlane/Inputs/REL/release1FP.shx
  avaframe/data/avaHockeySmall/Inputs/REL/release1HS.dbf
  avaframe/data/avaHockeySmall/Inputs/REL/release1HS.shp
  avaframe/data/avaHockeySmall/Inputs/REL/release1HS.shx
  avaframe/data/avaInclinedPlane/Inputs/REL/release1IP.dbf
  avaframe/data/avaInclinedPlane/Inputs/REL/release1IP.shp
  avaframe/data/avaInclinedPlane/Inputs/REL/release1IP.shx
  avaframe/data/avaParabola/Inputs/REL/release1PF.dbf
  avaframe/data/avaParabola/Inputs/REL/release1PF.shp
  avaframe/data/avaParabola/Inputs/REL/release1PF.shx
  avaframe/in3Utils/getReleaseArea.py
  avaframe/tests/test_getReleaseArea.py
Labels: bug

#1106 [com1]: changed a function call
  avaframe/com1DFA/particleTools.py
  avaframe/com1DFA/testSPH.py
Labels: bug

#1107 [doc]: fixed minor bugs in representation
  docs/DFAnumerics.rst
Labels: documentation

#1109 [com1] fix bug in plot that shows release thickness in release scenario of read from relTh file
  avaframe/com1DFA/com1DFA.py
  avaframe/out3Plot/outCom1DFA.py
Labels: bug

#1108 [com5; com6]: rename functions to be consistent with com1DFA
  avaframe/com5SnowSlide/com5SnowSlide.py
  avaframe/com6RockAvalanche/com6RockAvalanche.py
  avaframe/runCom5SnowSlide.py
  avaframe/runCom6RockAvalanche.py
  avaframe/tests/test_com5SnowSlide.py
  avaframe/tests/test_com6RockAvalanche.py
Labels: enhancement

#1111 [sys] Add Qlty (codeclimate replacement) and remove Codecov integration
  .github/workflows/runTestSinglePython.yml
  .qlty/qlty.toml
  README.md
  data/avaTest/Outputs/com1DFA/reports/releaseScenario_simLog.png
Labels: enhancement
