Repository avaframe/AvaFrame, pull requests merged in 2025-08, with the labels that each got.

#1159 [com4]: Add result file: minimum of travel length and travel angle
  avaframe/com4FlowPy/com4FlowPy.py
  avaframe/com4FlowPy/com4FlowPyCfg.ini
  avaframe/com4FlowPy/flowCore.py
  avaframe/runCom4FlowPy.py
  avaframe/tests/test_com4FlowPy.py
  docs/moduleCom4FlowPy.rst
Labels: enhancement, flowPyDev

#1172 [com6] scarpUpdate
  avaframe/com6RockAvalanche/scarp.py
  avaframe/in2Trans/shpConversion.py
  docs/moduleCom6RockAvalanche.rst
  pyproject.toml
Labels: enhancement

#1177 [com1]: Assign values to returned variables in every condition
  avaframe/com1DFA/DFAToolsCython.pyx
  avaframe/com1DFA/DFAfunctionsCython.pyx
  avaframe/com1DFA/checkCfg.py
  avaframe/com1DFA/damCom1DFA.pyx
  avaframe/tests/test_DFAfunctionsCython.py
  avaframe/tests/test_checkCfg.py
  avaframe/tests/test_com1DFA.py
Labels: bug, com1DFAdev
