Repository avaframe/AvaFrame, pull requests merged in 2025-05, with the labels that each got.

#1123 [com1] Add comment, fix small bug
  avaframe/com1DFA/deriveParameterSet.py
  avaframe/in3Utils/geoTrans.py
Labels: bug

#1127 [sys] add .gitattributes file to configure github linguist detection
  .gitattributes
Labels: enhancement

#1130 [runscripts] adjust log handling in project initialization
  avaframe/runScripts/runGenProjTopoRelease.py
  avaframe/runScripts/runInitializeProject.py
Labels: bug

#1131 [in2]: improve error messages for shape file validation
  avaframe/in2Trans/shpConversion.py
  avaframe/tests/test_shpConversion.py
Labels: bug, enhancement

#1095 [com4] use raster functions (for .asc and .tif) from AvaFrame
  avaframe/com4FlowPy/com4FlowPy.py
  avaframe/com4FlowPy/flowCore.py
  avaframe/com4FlowPy/rasterIo.py
  avaframe/com4FlowPy/splitAndMerge.py
  avaframe/runCom4FlowPy.py
  docs/moduleCom4FlowPy.rst
Labels: enhancement, flowPyDev

#1133 [com4]: delete rasterIo
  avaframe/com4FlowPy/rasterIo.py
Labels: flowPyDev
