Repository avaframe/AvaFrame, pull requests merged in 2025-01, with the labels that each got.

#1060 fix com2AB multiple lines issue [com2]
  avaframe/com2AB/com2AB.py
  avaframe/tests/test_com2AB.py
Labels: bug

#1056 update check for extent of mu, xi fields [com1]
  avaframe/com1DFA/checkCfg.py
  avaframe/com1DFA/com1DFA.py
  avaframe/com1DFA/com1DFACfg.ini
  avaframe/com1DFA/deriveParameterSet.py
  avaframe/tests/test_deriveParameterSet.py
Labels: enhancement

#1066 disable overlap checking for secrels; fixes #1065 [com1]
  avaframe/com1DFA/com1DFA.py
Labels: bug

#1067 [com4FlowPy]: new computation of zDeltaSum
  avaframe/com4FlowPy/flowCore.py
Labels: bug, flowPyDev

#1077 remove setting label for contourline at collections [out3]
  avaframe/out3Plot/statsPlots.py
Labels: bug
