Repository avaframe/AvaFrame, pull requests merged in 2025-02, with the labels that each got.

#1085 [sys] Upgrade twine and install pkginfo before upload
  .github/workflows/releaseWithManylinux.yml
  setup.py
Labels: bug

#1089 update the runscripts
  avaframe/ana1Tests/FPtest.py
  avaframe/ana1Tests/rotationTest.py
  avaframe/ana1Tests/rotationTestCfg.ini
  avaframe/com3Hybrid/com3HybridCfg.ini
  avaframe/data/avaFPtest/Inputs/FlatPlane_com1DFACfg.ini
  avaframe/out3Plot/outDistanceTimeAnalysis.py
  avaframe/out3Plot/outParticlesAnalysisCfg.ini
  avaframe/out3Plot/outQuickPlot.py
  avaframe/out3Plot/outTopo.py
  avaframe/out3Plot/statsPlots.py
  avaframe/runScripts/runAna3AIMECCompMods.py
  avaframe/runScripts/runContourPlot.py
  avaframe/runScripts/runFetchBench.py
  avaframe/runScripts/runParticleAnalysisPlots.py
  avaframe/runScripts/runPlotSimiSol.py
  avaframe/runScripts/runPlotTopo.py
  avaframe/runScripts/runProbAna.py
  avaframe/runScripts/runQuickPlotOne.py
  avaframe/runScripts/runRenaming.py
  avaframe/runScripts/runRotationTest.py
  avaframe/runScripts/runStandardTestsCom1DFAOrig.py
  avaframe/runScripts/runStatsPlots.py
  avaframe/runScripts/runTestFP.py
  avaframe/runScripts/runVariationsTestsCom1DFA.py
  avaframe/runScripts/runVariationsTestsCom1DFAOrig.py
  avaframe/runScripts/runWriteDesDict.py
  benchmarks/avaHockeyChannelStatsTest/avaHockeyChannelProbAna_probAnaCfg.ini
Labels: enhancement

#1094 Update documentation to reflect support for raster file formats (.asc and .tif); fixes #1082
  docs/com1DFAAlgorithm.rst
  docs/develop.rst
  docs/moduleAna3AIMEC.rst
  docs/moduleAna4Stats.rst
  docs/moduleCom1DFA.rst
  docs/moduleCom2AB.rst
  docs/moduleCom3Hybrid.rst
  docs/moduleIn2Trans.rst
  docs/moduleIn3Utils.rst
  docs/moduleOut1Peak.rst
Labels: documentation

#1084 [com4] Further mass redistribution/correction modifications
  avaframe/com4FlowPy/flowClass.py
Labels: enhancement

#1087 [com4FlowPy] minor Bugfix, documentation update and added feature for "forestFriciton", "forestDetrainment" and "forestFrictionLayer" model options
  avaframe/com4FlowPy/com4FlowPy.py
  avaframe/com4FlowPy/com4FlowPyCfg.ini
  avaframe/com4FlowPy/flowClass.py
  avaframe/com4FlowPy/flowCore.py
  avaframe/runCom4FlowPy.py
  docs/moduleCom4FlowPy.rst
  docs/theoryCom4FlowPy.rst
Labels: bug, documentation, enhancement

#1097 fix SyntaxWarning
  avaframe/in3Utils/geoTrans.py
Labels: enhancement

#1096 [com1;out3] add info on secrel, ent, res, and dam in releaseScenario plot
  avaframe/com1DFA/com1DFA.py
  avaframe/data/avaFPtest/Inputs/FlatPlane_com1DFACfg.ini
  avaframe/out1Peak/outPlotAllPeak.py
  avaframe/out3Plot/outCom1DFA.py
  avaframe/out3Plot/outParticlesAnalysis.py
  avaframe/tests/data/avaTestInputs/DAM/damLine.dbf
  avaframe/tests/data/avaTestInputs/DAM/damLine.prj
  avaframe/tests/data/avaTestInputs/DAM/damLine.shp
  avaframe/tests/data/avaTestInputs/DAM/damLine.shx
  avaframe/tests/data/avaTestInputs/ENT/entAlr.cpg
  avaframe/tests/data/avaTestInputs/ENT/entAlr.dbf
  avaframe/tests/data/avaTestInputs/ENT/entAlr.prj
  avaframe/tests/data/avaTestInputs/ENT/entAlr.shp
  avaframe/tests/data/avaTestInputs/ENT/entAlr.shx
  avaframe/tests/data/avaTestInputs/REL/relAlr.cpg
  avaframe/tests/data/avaTestInputs/REL/relAlr.dbf
  avaframe/tests/data/avaTestInputs/REL/relAlr.prj
  avaframe/tests/data/avaTestInputs/REL/relAlr.shp
  avaframe/tests/data/avaTestInputs/REL/relAlr.shx
  avaframe/tests/data/avaTestInputs/SECREL/ec1.dbf
  avaframe/tests/data/avaTestInputs/SECREL/ec1.prj
  avaframe/tests/data/avaTestInputs/SECREL/ec1.shp
  avaframe/tests/data/avaTestInputs/SECREL/ec1.shx
  avaframe/tests/test_com1DFA.py
Labels: enhancement

#1100 [in2;out3] Add profile plot
  avaframe/in2Trans/transformFields.py
  avaframe/out3Plot/outProfilePlots.py
  avaframe/runScripts/runD2Th.py
  avaframe/runScripts/runPlotAlongGivenProfile.py
  avaframe/tests/test_transformFields.py
Labels: enhancement
