Repository avaframe/AvaFrame, pull requests merged in 2025-07, with the labels that each got.

#1153 [com1] exporting of release and entrainment raster produced from shp files
  avaframe/com1DFA/com1DFA.py
  avaframe/com1DFA/com1DFACfg.ini
  avaframe/tests/test_com1DFA.py
Labels: enhancement

#1155 [runscript] adjust ranteTime to allow for reading result files without config file
  avaframe/runScripts/runRangeTimeDiagram.py
Labels: enhancement

#1157 chore(config): remove `.pep8speaks.yml` and update `pyproject.toml` Python support; docu com8 and coom9
  .pep8speaks.yml
  docs/introduction.rst
  docs/moduleCom8MoTPSA.rst
  docs/moduleCom9MoTVoellmy.rst
  pyproject.toml
Labels: documentation, enhancement

#1158 docs(index): add documentation for `com8MoTPSA` and `com9MoTVoellmy` modules
  docs/index.rst
Labels: documentation
